### ISSUE TITLE
updating a configuration in controller doesn't result in callback

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-sdk-c#108]
When renaming a service the CSDK will get two service callbacks - one with `ZITI_SERVICE_UNAVAILABLE` and one with `ZITI_OK`.  This will allow an sdk-based app to remove an intercept/add it back properly.  

If the config for that service changes - the CSDK will get a service callback with `ZITI_OK` only.

*steps to reproduce*
- establish a service in controller
- establish a csdk session to the service
- update the service's config
- observe `ZITI_OK` callback only

**Comment by ekoby** [comment]
ZITI_SERVICE_UNAVAILABLE seems like incorrect expectation. ZITI_OK indicates new or updated service, app should check relevant configs for changes

**Comment by dovholuknf** [comment]
So an update to the config is left to the SDK consumer to 'figure it out'? That's not a friendly implementation and I think the SDK should be more friendly than that. Perhaps additional status baked into the result as a flag? or 'something'?

**Comment by dovholuknf** [comment]
Updated title to "updating a configuration in controller doesn't result in callback". When an 'internal' config change to either `ziti-tunneler-server.v1` or `ziti-tunneler-client.v1` happens - the csdk should trigger a callback. Right now that doesn't happen
