### ISSUE TITLE
ziti_shutdown doesn't guard against NULL/incomplete intialized context

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-sdk-c#111]
I had a context which did not fully initialize due to ` failed to login: INVALID_AUTH[-12](The authentication request failed)`. When that context is passed to ziti_shutdown `ztx->session` is NULL and `free_ziti_session(ztx->session);` will cause a crash

**Comment by ekoby** [comment]
`free_ziti_session` calls `model_free()` (https://github.com/openziti/ziti-sdk-c/blob/master/library/model_support.c#L193) which guards against NULL pointer being passed
