### ISSUE TITLE
rework ziti_close() and ziti_connection lifecycle

### ISSUE THREAD

**Issue by ekoby** [openziti/ziti-sdk-c#154]
fix/improve constency of ziti_connection lifecycle:
- currently ZITI_EOF must be handled differently from other errors by the application code
- may need to require app to call ziti_close() even after receiving error on ziti_conn
- ziti_close() with a callback -- make it closer to libuv standards

**Comment by smilindave26** [comment]
+1 on ziti_close() with a callback.  There are some gyrations in some of the Apple stuff to work around this...
