### ISSUE TITLE
crash when ziti identity is invalid

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-sdk-c#416]
during the ip->dns migration many users had "garbage" replaced in the identity file. When there's an invalid URL in the ztAPI, the SDK crashes. It should not crash.

![image](https://user-images.githubusercontent.com/46322585/174941416-a9e442d9-13a4-4f3d-b9e8-0a1fadca17a8.png)

**Comment by 0xc0dedad** [comment]
@dovholuknf,
I'd like to handle this issue. Please assign it to me.

**Comment by dovholuknf** [comment]
You got it. Thanks!
