### ISSUE TITLE
Multiple simultaneous calls to NF_init() hangs the C-SDK

### ISSUE THREAD

**Issue by rentallect** [openziti/ziti-sdk-c#45]
to reproduce, just call NF_init() multiple times in a row:

```
     NF_init();
     NF_init();
     NF_init();
```

The NodeJS-SDK, while handling some startup sequences in an Electron app, sometimes does multiple NF_init() calls to the C-SDK, and experiences hangs.

**Comment by ekoby** [comment]
each `NF_init()` will create a new `nf_context `separate from others. This is probably not a common pattern but it is not invalid. If that is not desired (I assume it is not) -- you should prevent `NF_init()` from being called multiple times, or have your callbacks handle multiple instances of `nf_context`.

**Comment by rentallect** [comment]
Upon encountering this issue, I worked around it by taking steps in the JS layer (added a mutex lock to guard the main Ziti initialization sequence) to prevent multiple simultaneous NF_init() calls from being done if app launches multiple HTTP requests the instant it starts up.  If the c-sdk creates a new nf_context for each NF_init() call that's fine, as long as it doesn't hang while attempting to produce them in cases where they are being produced simultaneously.
