### ISSUE TITLE
Ziti_load_context and ziti_init should take a byte array/function - not just a file

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-sdk-c#462]
Ziti_load_context currently expects to load a file from the drive. That's helpful but it'd be as helpful to take a byte array or a function to return a byte array or something that would allow me to pass something other than a file

**Comment by qrkourier** [comment]
Would this make it possible for tunnelers and other SDK implementations that import the C SDK to start accepting the Ziti identity config as an environment variable? It sounds like you're saying the C SDK itself can only load the config from a file.

**Comment by dovholuknf** [comment]
it'd lay the groundwork for that - yes. The tunneler would be able to read the env var, convert it to a byte array/function and pass it to the c sdk to load the identity.
