### ISSUE TITLE
Zitilib - logging

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti-sdk-c#468]
Right now using `Ziti C SDK version 0.30.1-118 @c9a2f03` I still see log levels at VERBOSE and I can't seem to discover the mechanism to control the log level. Is there a function to control the log level? 

Accordingly, there's no way for me to supply the logging callback to be executed. I'd like to control logging in my application, and log to where I choose to log.

**Comment by qrkourier** [comment]
[Possibly related issue](https://github.com/openziti/ziti-tunnel-sdk-c/issues/531) with T-SDK's `ziti-edge-tunnel run --verbose N` no longer functioning and related precedence of the tunneler config.json file's `LogLevel` property.

**Comment by scareything** [comment]
The issue @qrkourier mentions is specific to ziti-edge-tunnel, which I gather is not in play here.

An issue related to logging setup was fixed in ziti-sdk-c recently. See https://github.com/openziti/ziti-sdk-c/pull/464

**Comment by dovholuknf** [comment]
fixed with 0.30.4
