### ISSUE TITLE
Edge Router connection drops during large transfer

### ISSUE THREAD

**Issue by ekoby** [openziti/ziti-sdk-c#478]
from: https://openziti.discourse.group/t/zet-random-loss-of-connection-during-usage/884

some observations:
- it seems that  disconnect happens due to a timed out latency probe (all other paths have associated error logging)
- on channel disconnect incoming buffer is not cleared which causes :point_down: messages after reconnect
```
Nov 22 21:42:06 MACHINE_C ziti-edge-tunnel[448251]: (448251)[     2011.846]   ERROR ziti-sdk:channel.c:496 dispatch_message() ch[0] received message without conn_id or for unknown connection ct[ED72] conn_id[9]
Nov 22 21:42:06 MACHINE_C ziti-edge-tunnel[448251]: (448251)[     2011.846]   ERROR ziti-sdk:channel.c:485 dispatch_message() ch[0] received unexpected message ct[ED72] in Connecting state
```

**Comment by johnalotoski** [comment]
Attached below is a file containing ziti-edge-tunnel logs with verbosity 6 starting at systemd service startup to several log lines after a disconnect event:

[zet-disconnect-verbosity-6.log](https://github.com/openziti/ziti-sdk-c/files/10076474/zet-disconnect-verbosity-6.log)
