### ISSUE TITLE
Edge router not removed by ZET when deleted from network and timeouts

### ISSUE THREAD

**Issue by gormami** [openziti/ziti-sdk-c#614]
When an Edge Router is deleted from a network, ZET fails on the channel, but keeps attempting to reconnect on that channel.  While in this state, dials from this instance timeout in an odd way.  Testing shows the fabric circuit is created per the controller (fabric.circuit created event), but the actual path does not complete until the timeout on the originating tunneler.  Packet traces show that the SYN packet and intial connection are not emitted from the hosting ER until the timeout of the dialer.  It appears a final message is being "held" until the timeout.  This appears to only happen on "dial only" tunnelers.  Hosting nodes see the deletion and act accordingly.

**Comment by ekoby** [comment]
the cause is stale ER information is the session
