### ISSUE TITLE
load_file returns incorrect status when uv_fs_open fails due to permission denied

### ISSUE THREAD

**Issue by scareything** [openziti/ziti-sdk-c#690]
`load_file` only checks the return value of `uv_fs_open` for -1, but [`uv_fs_open` may return other negative values in some circumstances](https://github.com/libuv/libuv/blob/v1.x/src/win/fs.c#L70), e.g. permission denied, when a callback is not specified.

**Comment by ekoby** [comment]
fixed in #691
